/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_ADAS__Syst_Status__Service_PROXY_HPP_
#define V1_COMMONAPI_ADAS__Syst_Status__Service_PROXY_HPP_

#include <v1/commonapi/ADAS_SystStatus_ServiceProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

template <typename ... _AttributeExtensions>
class ADAS_SystStatus_ServiceProxy
    : virtual public ADAS_SystStatus_Service,
      virtual public ADAS_SystStatus_ServiceProxyBase,
      virtual public _AttributeExtensions... {
public:
    ADAS_SystStatus_ServiceProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ADAS_SystStatus_ServiceProxy();

    typedef ADAS_SystStatus_Service InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute ADAS_SystStatus.
     */
    virtual ADAS_SystStatusAttribute& getADAS_SystStatusAttribute() {
        return delegate_->getADAS_SystStatusAttribute();
    }



 private:
    std::shared_ptr< ADAS_SystStatus_ServiceProxyBase> delegate_;
};

typedef ADAS_SystStatus_ServiceProxy<> ADAS_SystStatus_ServiceProxyDefault;

namespace ADAS_SystStatus_ServiceExtensions {
    template <template <typename > class _ExtensionType>
    class ADAS_SystStatusAttributeExtension {
     public:
        typedef _ExtensionType< ADAS_SystStatus_ServiceProxyBase::ADAS_SystStatusAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< ADAS_SystStatus_ServiceProxyBase::ADAS_SystStatusAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        ADAS_SystStatusAttributeExtension(ADAS_SystStatus_ServiceProxyBase& proxy): attributeExtension_(proxy.getADAS_SystStatusAttribute()) {
        }
    
        inline extension_type& getADAS_SystStatusAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace ADAS_SystStatus_ServiceExtensions

//
// ADAS_SystStatus_ServiceProxy Implementation
//
template <typename ... _AttributeExtensions>
ADAS_SystStatus_ServiceProxy<_AttributeExtensions...>::ADAS_SystStatus_ServiceProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< ADAS_SystStatus_ServiceProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< ADAS_SystStatus_ServiceProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ADAS_SystStatus_ServiceProxy<_AttributeExtensions...>::~ADAS_SystStatus_ServiceProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &ADAS_SystStatus_ServiceProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ADAS_SystStatus_ServiceProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ADAS_SystStatus_ServiceProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ADAS_SystStatus_ServiceProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ADAS_SystStatus_ServiceProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> ADAS_SystStatus_ServiceProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace commonapi
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::commonapi::ADAS_SystStatus_ServiceProxy,
    _AttributeExtension> {
    typedef typename ::v1::commonapi::ADAS_SystStatus_ServiceProxy<
            ::v1::commonapi::ADAS_SystStatus_ServiceExtensions::ADAS_SystStatusAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_ADAS__Syst_Status__Service_PROXY_HPP_
