/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/ADAS_SystStatus_ServiceSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createADAS_SystStatus_ServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< ADAS_SystStatus_ServiceSomeIPProxy>(_address, _connection);
}

void initializeADAS_SystStatus_ServiceSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.ADAS_SystStatus_Service:v1_0:commonapi.ADAS_SystStatus_Service",
        0x3331, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.ADAS_SystStatus_Service:v1_0",
        &createADAS_SystStatus_ServiceSomeIPProxy);
}

INITIALIZER(registerADAS_SystStatus_ServiceSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeADAS_SystStatus_ServiceSomeIPProxy);
}

ADAS_SystStatus_ServiceSomeIPProxy::ADAS_SystStatus_ServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          aDAS_SystStatus_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x9910), CommonAPI::SomeIP::event_id_t(0x9910), CommonAPI::SomeIP::method_id_t(0x1910), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, static_cast< ::v1::commonapi::ADAS_SystStatus_Service_::ADAS_SystStatus_StructDeployment_t* >(nullptr))
{
}

ADAS_SystStatus_ServiceSomeIPProxy::~ADAS_SystStatus_ServiceSomeIPProxy() {
    completed_.set_value();
}

ADAS_SystStatus_ServiceSomeIPProxy::ADAS_SystStatusAttribute& ADAS_SystStatus_ServiceSomeIPProxy::getADAS_SystStatusAttribute() {
    return aDAS_SystStatus_;
}


void ADAS_SystStatus_ServiceSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> ADAS_SystStatus_ServiceSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace commonapi
} // namespace v1
